import DashboardLayout from "@/components/DashboardLayout";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { trpc } from "@/lib/trpc";
import { Activity, BarChart3, ClipboardCheck, UsersRound } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export default function AdminDashboard() { return <ProtectedRoute adminOnly><AdminDashboardContent /></ProtectedRoute>; }

function AdminDashboardContent() {
  const metrics = trpc.admin.metrics.useQuery();
  const data = metrics.data;
  return <DashboardLayout area="admin"><div className="page-enter"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d46c58]">Panorama da plataforma</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-[-.045em] text-[#123f3b]">Visão geral</h1><p className="mt-3 text-sm leading-6 text-[#66837c]">Acompanhe dados operacionais com base nos registros reais da Mental Saúde.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminMetric icon={UsersRound} label="Usuários" value={data?.totalUsers ?? 0} hint="Contas cadastradas" /><AdminMetric icon={ClipboardCheck} label="Testes realizados" value={data?.totalAttempts ?? 0} hint="Inclui avaliações em andamento" /><AdminMetric icon={Activity} label="Conclusões" value={data?.completedAttempts ?? 0} hint="Avaliações finalizadas" /><AdminMetric icon={BarChart3} label="Testes publicados" value={data?.activeAssessments ?? 0} hint="Disponíveis no catálogo" /></section><section className="mt-6 rounded-3xl border border-[#dce9e4] bg-[#fffefa] p-6 sm:p-7"><div><p className="text-sm font-semibold text-[#0a7066]">Engajamento por teste</p><h2 className="mt-2 font-display text-2xl font-semibold text-[#173e39]">Volume de registros</h2></div>{metrics.isLoading ? <div className="mt-7 h-64 animate-pulse rounded-2xl bg-[#eef6f2]" /> : data?.resultsByAssessment?.some(item => item.count > 0) ? <div className="mt-7 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.resultsByAssessment} margin={{ left: -18, right: 4, top: 10 }}><CartesianGrid vertical={false} stroke="#e7efec" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#69867f", fontSize: 11 }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: "#69867f", fontSize: 11 }} /><Tooltip cursor={{ fill: "#edf6f2" }} contentStyle={{ borderRadius: 12, border: "1px solid #dce9e4" }} /><Bar dataKey="count" fill="#0b7167" radius={[8, 8, 0, 0]} maxBarSize={52} /></BarChart></ResponsiveContainer></div> : <div className="mt-7 rounded-2xl bg-[#f2f8f5] px-6 py-14 text-center"><BarChart3 className="mx-auto h-7 w-7 text-[#5bb5a8]" /><p className="mt-3 text-sm font-semibold text-[#365b54]">Os indicadores aparecerão quando houver uso.</p><p className="mt-1 text-xs text-[#728f88]">Publique testes e acompanhe os dados à medida que as pessoas concluírem suas autoavaliações.</p></div>}</section></div></DashboardLayout>;
}

function AdminMetric({ icon: Icon, label, value, hint }: { icon: typeof UsersRound; label: string; value: number; hint: string }) { return <article className="rounded-2xl border border-[#dce9e4] bg-[#fffefa] p-5"><Icon className="h-5 w-5 text-[#0b7167]" /><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-[#71948c]">{label}</p><p className="mt-2 font-display text-3xl font-semibold text-[#193f39]">{value}</p><p className="mt-1 text-xs text-[#718f88]">{hint}</p></article>; }
