import { Brand } from "@/components/Brand";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

type LegalPageProps = { kind: "terms" | "privacy" };

export default function LegalPage({ kind }: LegalPageProps) {
  const isTerms = kind === "terms";
  return <div className="min-h-screen bg-[#f7f6ef] text-[#153a36]"><header className="mx-auto flex h-20 max-w-[960px] items-center justify-between px-5 sm:px-8"><div className="flex items-center gap-6"><Brand compact /><Link href="/conteudos" className="text-sm font-semibold text-[#3b5d56] transition-colors hover:text-[#0b7167]">Conteúdos</Link></div><Link href="/testes" className="inline-flex items-center text-sm font-semibold text-[#0a615a]"><ArrowLeft className="mr-2 h-4 w-4" />Voltar ao catálogo</Link></header><main className="mx-auto max-w-[820px] px-5 pb-20 pt-10 sm:px-8"><div className="rounded-[2rem] border border-[#d9e9e4] bg-[#fffefa] p-7 shadow-[0_26px_55px_-46px_rgba(11,70,62,.8)] sm:p-12"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#e7f5f0] text-[#0b7167]"><ShieldCheck className="h-6 w-6" /></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#58ab9e]">Mental Saúde</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-[-.04em] text-[#173e39]">{isTerms ? "Termos de Uso" : "Política de Privacidade"}</h1><p className="mt-3 text-sm text-[#66837c]">Versão informativa · agosto de 2026</p></div></div>{isTerms ? <TermsContent /> : <PrivacyContent />}</div></main></div>;
}

function TermsContent() { return <div className="mt-10 space-y-8 text-sm leading-7 text-[#52736b]"><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">1. Finalidade da plataforma</h2><p className="mt-3">A Mental Saúde oferece conteúdos educativos e instrumentos de autoavaliação para apoiar o autoconhecimento. As autoavaliações não são diagnóstico, triagem clínica completa, psicoterapia ou atendimento médico.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">2. Uso responsável</h2><p className="mt-3">O usuário deve responder de forma voluntária e interromper a experiência se ela causar desconforto. Resultados devem ser interpretados no contexto da própria vida e, quando necessário, discutidos com profissional habilitado.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">3. Situações urgentes</h2><p className="mt-3">A plataforma não monitora emergências. Em uma situação de risco imediato, procure um serviço de urgência da sua região. No Brasil, o CVV atende pelo número 188 para apoio emocional.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">4. Resultados e exportação</h2><p className="mt-3">O resultado é uma devolutiva educativa baseada nas respostas enviadas. O usuário logado pode exportar uma cópia do resultado em PDF para seu próprio registro, sem que isso altere o histórico salvo na plataforma.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">5. Aceite</h2><p className="mt-3">Antes da primeira autoavaliação, o usuário deve confirmar que leu estes Termos de Uso, a Política de Privacidade e os limites da experiência. O aceite é registrado com a versão vigente do documento.</p></section></div>; }
function PrivacyContent() { return <div className="mt-10 space-y-8 text-sm leading-7 text-[#52736b]"><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">1. Dados tratados</h2><p className="mt-3">Para disponibilizar a plataforma, podemos tratar dados de conta fornecidos pelo Manus OAuth, dados de perfil que você escolher informar e respostas/resultados das autoavaliações que você decidir concluir.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">2. Finalidade</h2><p className="mt-3">Os dados são utilizados para autenticar sua conta, exibir seu histórico, calcular devolutivas, apresentar recomendações gerais e permitir que você gerencie seu perfil.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">3. Controle do usuário</h2><p className="mt-3">Você pode revisar seu perfil e suas preferências na área autenticada. A exportação em PDF é iniciada pelo próprio usuário e é gerada localmente no navegador.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">4. Limites</h2><p className="mt-3">Nenhum conteúdo da plataforma deve ser utilizado como substituto de avaliação profissional. Evite compartilhar o PDF ou seus resultados com terceiros sem considerar sua privacidade.</p></section><section><h2 className="font-display text-2xl font-semibold text-[#173e39]">5. Atualizações</h2><p className="mt-3">Esta política pode ser atualizada para refletir mudanças de produto ou requisitos legais. Quando houver uma nova versão relevante, o consentimento poderá ser solicitado novamente.</p></section></div>; }
